In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
Dataset=pd.read_csv('insurance_pre.csv')

In [3]:
Dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
Dataset=pd.get_dummies(Dataset,dtype=int,drop_first=True)
Dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
Dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
Independent=Dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
Independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [7]:
Dependent=Dataset[[ 'charges']]
Dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
#standardisation

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
Independent=sc.fit_transform(Independent)

In [9]:
#GridSearchCV

from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],'max_features': [None,'sqrt','log2'],'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)

# fitting the model for grid search
grid.fit(Independent,Dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
60 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'friedman_mse', 'absolute_error', 'poisson'}. Got 'mse' instead.

--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'squared_error', 'friedman_mse', 'poisson'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'squared_error', 'poisson', 'friedman_mse'}. Got 'mse' instead.

--------------------------------------------------------------------------------
7 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'poisson', 'squared_error', 'friedman_mse'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'absolute_error', 'poisson', 'friedman_mse'}. Got 'mse' instead.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'poisson', 'friedman_mse', 'squared_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'poisson', 'friedman_mse', 'absolute_error', 'squared_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'friedman_mse', 'poisson', 'absolute_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'absolute_error', 'poisson', 'friedman_mse'}. Got 'mae' instead.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'poisson', 'squared_error', 'friedman_mse'}. Got 'mae' instead.

--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'squared_error', 'friedman_mse', 'poisson'}. Got 'mae' instead.

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'poisson', 'friedman_mse', 'squared_error'}. Got 'mae' instead.

--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'poisson', 'friedman_mse', 'absolute_error', 'squared_error'}. Got 'mae' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.71000165 0.69172369 0.70115042 0.63306418 0.70543735 0.67585026]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [10]:
re=grid.cv_results_
re

{'mean_fit_time': array([0.00019855, 0.00200071, 0.00048609, 0.00099096, 0.0020606 ,
        0.00082998, 0.00066414, 0.0012486 , 0.00041199, 0.00080314,
        0.00071836, 0.00076056, 0.00589623, 0.0048562 , 0.00377331,
        0.00549955, 0.00199327, 0.00322533]),
 'std_fit_time': array([0.00039711, 0.00311885, 0.00040279, 0.00040053, 0.002231  ,
        0.00069383, 0.00012738, 0.00101577, 0.0002079 , 0.00025808,
        0.00026304, 0.00027709, 0.00128198, 0.00113914, 0.00121653,
        0.00270392, 0.00088765, 0.00154768]),
 'mean_score_time': array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00154729, 0.00214515, 0.00197673,
        0.00138731, 0.00273385, 0.00245471]),
 'std_score_time': array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00092732, 0.00199935, 0.00136366,
        0.00088577, 0.00242065, 0.00176761]),
 'param_criterion': masked_array(data=['mse', 'mse', 'mse', 'mse', 'mse', 'mse', 'mae', 'mae',
                    'mae', 'mae', 'mae', 'mae', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=[None, None, 'sqrt', 'sqrt', 'log2', 'log2', None, None,
                    'sqrt', 'sqrt', 'log2', 'log2', None, None, 'sqrt',
                    'sqrt', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'mse', 'max_features': None, 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': None, 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': None, 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': None, 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': None, 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': None, 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'random'}],
 'split0_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.72412989, 0.75827015, 0.75474665,
        0.54497828, 0.72494217, 0.60141671]),
 'split1_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.66081145, 0.62769308, 0.53204502,
        0.57254868, 0.63251319, 0.56040507]),
 'split2_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.73378302, 0.72005108, 0.77994364,
        0.71718825, 0.77900949, 0.8010034 ]),
 'split3_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.73685316, 0.68088754, 0.70532722,
        0.65944844, 0.67389084, 0.70806759]),
 'split4_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.69443072, 0.67171658, 0.73368959,
        0.67115726, 0.71683106, 0.70835854]),
 'mean_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.71000165, 0.69172369, 0.70115042,
        0.63306418, 0.70543735, 0.67585026]),
 'std_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.0288038 , 0.0443813 , 0.08803841,
        0.0642578 , 0.04946965, 0.08558738]),
 'rank_test_score': array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 1, 4, 3, 6, 2, 5])}

In [11]:
Table=pd.DataFrame. from_dict(re)
Table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000199,0.000397,0.000000,0.000000,mse,None,best,"{'criterion': 'mse', 'max_features': None, 'sp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
1,0.002001,0.003119,0.000000,0.000000,mse,None,random,"{'criterion': 'mse', 'max_features': None, 'sp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
2,0.000486,0.000403,0.000000,0.000000,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
3,0.000991,0.000401,0.000000,0.000000,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
4,0.002061,0.002231,0.000000,0.000000,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
5,0.000830,0.000694,0.000000,0.000000,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
6,0.000664,0.000127,0.000000,0.000000,mae,None,best,"{'criterion': 'mae', 'max_features': None, 'sp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
7,0.001249,0.001016,0.000000,0.000000,mae,None,random,"{'criterion': 'mae', 'max_features': None, 'sp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
8,0.000412,0.000208,0.000000,0.000000,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
9,0.000803,0.000258,0.000000,0.000000,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
10,0.000718,0.000263,0.000000,0.000000,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
11,0.000761,0.000277,0.000000,0.000000,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
12,0.005896,0.001282,0.001547,0.000927,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.724130,0.660811,0.733783,0.736853,0.694431,0.710002,0.028804,1
13,0.004856,0.001139,0.002145,0.001999,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.758270,0.627693,0.720051,0.680888,0.671717,0.691724,0.044381,4
14,0.003773,0.001217,0.001977,0.001364,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.754747,0.532045,0.779944,0.705327,0.733690,0.701150,0.088038,3
15,0.005500,0.002704,0.001387,0.000886,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.544978,0.572549,0.717188,0.659448,0.671157,0.633064,0.064258,6
16,0.001993,0.000888,0.002734,0.002421,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.724942,0.632513,0.779009,0.673891,0.716831,0.705437,0.049470,2
17,0.003225,0.001548,0.002455,0.001768,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.601417,0.560405,0.801003,0.708068,0.708359,0.675850,0.085587,5

In [12]:
grid_predictions = grid.predict(Independent)

In [13]:
print(' R_score for best parameter{}:'.format(grid.best_params_))

 R_score for best parameter{'criterion': 'friedman_mse', 'max_features': None, 'splitter': 'best'}:

In [14]:
from sklearn.metrics import r2_score
R_score=r2_score(Dependent,grid_predictions)
R_score

0.998667156135576

In [15]:
#Saving the Model

import pickle
filename="finalized_model_Decision_Tree.sav"
pickle.dump(grid_predictions,open(filename,'wb'))

In [16]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 30
BMI: 25
Children: 1
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 0

In [17]:
Preinput=sc.transform([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
Preinput

C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-0.65555117, -0.92904899, -0.07876719, -1.0105187 , -0.5074631 ]])

In [18]:
loaded_model=pickle.load(open("finalized_model_Decision_Tree.sav",'rb'))
Future_Prediction=grid.predict(Preinput)
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[4527.18295]