In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
Dataset=pd.read_csv('insurance_pre.csv')

In [3]:
Dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
Dataset=pd.get_dummies(Dataset,dtype=int,drop_first=True)
Dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
Dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
Independent=Dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
Independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [7]:
Dependent=Dataset[[ 'charges']]
Dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import GridSearchCV

from sklearn.tree import DecisionTreeRegressor

param_grid = {'criterion':['mse','mae','friedman_mse'],
'max_features': [None,'sqrt','log2'],
'splitter':['best','random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(Independent,Dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
60 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'squared_error', 'poisson', 'absolute_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
17 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'absolute_error', 'squared_error', 'poisson'}. Got 'mse' instead.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'poisson', 'squared_error', 'friedman_mse'}. Got 'mse' instead.

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'poisson', 'absolute_error', 'friedman_mse'}. Got 'mse' instead.

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'poisson', 'friedman_mse', 'absolute_error', 'squared_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'friedman_mse', 'absolute_error', 'poisson'}. Got 'mse' instead.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'poisson', 'absolute_error', 'squared_error', 'friedman_mse'}. Got 'mse' instead.

--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'absolute_error', 'squared_error', 'poisson'}. Got 'mae' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.69280309 0.6841999  0.67734191 0.64642211 0.70880582 0.66789156]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [15]:
re=grid.cv_results_
re

{'mean_fit_time': array([0.00165215, 0.00150743, 0.00102344, 0.00083733, 0.00179214,
        0.00130796, 0.00120001, 0.00070481, 0.00145636, 0.000598  ,
        0.00050025, 0.00152521, 0.00879197, 0.005972  , 0.00585351,
        0.00837927, 0.01531081, 0.00666718]),
 'std_fit_time': array([0.00143227, 0.00077954, 0.00056847, 0.00052118, 0.00054066,
        0.00139124, 0.00040004, 0.00075507, 0.00053084, 0.00048828,
        0.00063282, 0.00043962, 0.0009803 , 0.0022864 , 0.00252536,
        0.00331237, 0.01200978, 0.00364733]),
 'mean_score_time': array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00188956, 0.00388136, 0.0031795 ,
        0.0024291 , 0.00257049, 0.00350161]),
 'std_score_time': array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00167274, 0.00389959, 0.00320389,
        0.00216356, 0.00156944, 0.00258276]),
 'param_criterion': masked_array(data=['mse', 'mse', 'mse', 'mse', 'mse', 'mse', 'mae', 'mae',
                    'mae', 'mae', 'mae', 'mae', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=[None, None, 'sqrt', 'sqrt', 'log2', 'log2', None, None,
                    'sqrt', 'sqrt', 'log2', 'log2', None, None, 'sqrt',
                    'sqrt', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'mse', 'max_features': None, 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': None, 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': None, 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': None, 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': None, 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': None, 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'random'}],
 'split0_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.71061714, 0.63446198, 0.58171135,
        0.67971317, 0.76833966, 0.75496157]),
 'split1_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.64765504, 0.67208683, 0.64527116,
        0.57940618, 0.5874988 , 0.53972201]),
 'split2_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.73027375, 0.69732509, 0.67166471,
        0.74551798, 0.74596715, 0.69582326]),
 'split3_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.7034585 , 0.66717577, 0.72064753,
        0.60608732, 0.67505028, 0.74020065]),
 'split4_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.67201103, 0.74994981, 0.76741483,
        0.6213859 , 0.76717319, 0.60875032]),
 'mean_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.69280309, 0.6841999 , 0.67734191,
        0.64642211, 0.70880582, 0.66789156]),
 'std_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan, 0.02934479, 0.03848566, 0.0635523 ,
        0.05945272, 0.06955116, 0.08187196]),
 'rank_test_score': array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 2, 3, 4, 6, 1, 5])}

In [10]:
Table=pd.DataFrame. from_dict(re)
Table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001652,0.001432,0.000000,0.000000,mse,None,best,"{'criterion': 'mse', 'max_features': None, 'sp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
1,0.001507,0.000780,0.000000,0.000000,mse,None,random,"{'criterion': 'mse', 'max_features': None, 'sp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
2,0.001023,0.000568,0.000000,0.000000,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
3,0.000837,0.000521,0.000000,0.000000,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
4,0.001792,0.000541,0.000000,0.000000,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
5,0.001308,0.001391,0.000000,0.000000,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
6,0.001200,0.000400,0.000000,0.000000,mae,None,best,"{'criterion': 'mae', 'max_features': None, 'sp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
7,0.000705,0.000755,0.000000,0.000000,mae,None,random,"{'criterion': 'mae', 'max_features': None, 'sp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
8,0.001456,0.000531,0.000000,0.000000,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
9,0.000598,0.000488,0.000000,0.000000,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
10,0.000500,0.000633,0.000000,0.000000,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
11,0.001525,0.000440,0.000000,0.000000,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
12,0.008792,0.000980,0.001890,0.001673,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.710617,0.647655,0.730274,0.703458,0.672011,0.692803,0.029345,2
13,0.005972,0.002286,0.003881,0.003900,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.634462,0.672087,0.697325,0.667176,0.749950,0.684200,0.038486,3
14,0.005854,0.002525,0.003180,0.003204,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.581711,0.645271,0.671665,0.720648,0.767415,0.677342,0.063552,4
15,0.008379,0.003312,0.002429,0.002164,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.679713,0.579406,0.745518,0.606087,0.621386,0.646422,0.059453,6
16,0.015311,0.012010,0.002570,0.001569,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.768340,0.587499,0.745967,0.675050,0.767173,0.708806,0.069551,1
17,0.006667,0.003647,0.003502,0.002583,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.754962,0.539722,0.695823,0.740201,0.608750,0.667892,0.081872,5

In [17]:
grid_predictions = grid.predict(Independent)

In [18]:
print(' R_score for best parameter{}:'.format(grid.best_params_))

 R_score for best parameter{'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'}:

In [19]:
from sklearn.metrics import r2_score
R_score=r2_score(Dependent,grid_predictions)
R_score

0.998667156135576