In [1]:
#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Loading Dataset
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#checking counts-Rows&columns
dataset.shape

(400, 5)

In [4]:
#get dummies
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [5]:
#dropping the column that is not required which has no information
dataset=dataset.drop("User ID",axis=1)
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [6]:
#How many classes we are going to classify
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [7]:
#spliting Independent and Dependent
Independent=dataset[["Age","EstimatedSalary","Gender_Male"]]
Dependent=dataset["Purchased"]

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Independent,Dependent, test_size = 1/3, random_state = 0)

In [9]:
#StandardScaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [10]:
#model creation
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy','log_loss'],'max_features': [None,'sqrt','log2'],'splitter':['best','random'],'random_state':[None]} 
grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'random_state': [None],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [20]:
grid_predictions = grid.predict(X_test)

In [21]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_random_state,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005755,0.003142,0.005598,0.001963,gini,None,None,best,"{'criterion': 'gini', 'max_features': None, 'r...",0.849794,0.849057,0.833323,0.870362,0.924528,0.865413,0.031813,3
1,0.004665,0.002385,0.004990,0.000891,gini,None,None,random,"{'criterion': 'gini', 'max_features': None, 'r...",0.826263,0.813511,0.811321,0.813179,0.865054,0.825866,0.020303,14
2,0.002974,0.002623,0.005272,0.003716,gini,sqrt,None,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.829615,0.825959,0.796284,0.944161,0.885265,0.856257,0.052523,5
3,0.002640,0.002073,0.003490,0.002121,gini,sqrt,None,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.867478,0.813511,0.796284,0.831098,0.883278,0.838330,0.032576,10
4,0.008281,0.007007,0.004543,0.002990,gini,log2,None,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.804764,0.811321,0.796284,0.867097,0.883278,0.832549,0.035510,12
5,0.004324,0.000457,0.005447,0.003415,gini,log2,None,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.812243,0.793754,0.793565,0.832483,0.801281,0.806665,0.014594,18
6,0.002655,0.000733,0.003982,0.001479,entropy,None,None,best,"{'criterion': 'entropy', 'max_features': None,...",0.849794,0.868752,0.814409,0.925272,0.924528,0.876551,0.043160,1
7,0.004990,0.002070,0.002659,0.000729,entropy,None,None,random,"{'criterion': 'entropy', 'max_features': None,...",0.732497,0.831253,0.758030,0.906166,0.906166,0.826822,0.072443,13
8,0.003539,0.001151,0.004233,0.001201,entropy,sqrt,None,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.787654,0.868752,0.796284,0.851527,0.808775,0.822599,0.031849,15
9,0.003119,0.001208,0.004111,0.001714,entropy,sqrt,None,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.799620,0.849057,0.738451,0.906166,0.923510,0.843361,0.068294,8
10,0.003419,0.000746,0.002992,0.001787,entropy,log2,None,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.826263,0.888107,0.814409,0.870362,0.883278,0.856484,0.030312,4
11,0.002407,0.001404,0.003659,0.002032,entropy,log2,None,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.765716,0.849057,0.795256,0.905069,0.885265,0.840073,0.052697,9
12,0.004196,0.002844,0.004039,0.002423,log_loss,None,None,best,"{'criterion': 'log_loss', 'max_features': None...",0.849794,0.868752,0.814409,0.906935,0.924528,0.872884,0.039487,2
13,0.004179,0.001548,0.003470,0.000827,log_loss,None,None,random,"{'criterion': 'log_loss', 'max_features': None...",0.808927,0.811321,0.813179,0.851527,0.903610,0.837713,0.036498,11
14,0.004446,0.001762,0.003482,0.002073,log_loss,sqrt,None,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.804764,0.870047,0.831098,0.867097,0.905069,0.855615,0.034562,6
15,0.004134,0.002115,0.003784,0.001362,log_loss,sqrt,None,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.804764,0.811321,0.833323,0.775815,0.883278,0.821700,0.035852,16
16,0.003971,0.000915,0.003804,0.000413,log_loss,log2,None,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.782557,0.868752,0.815056,0.886792,0.867097,0.844051,0.038962,7
17,0.003836,0.000891,0.003370,0.001316,log_loss,log2,None,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.847141,0.846714,0.811321,0.796284,0.805463,0.821384,0.021400,17

In [22]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': None, 'random_state': None, 'splitter': 'best'}

In [23]:
#evaluation metrics(confusion_matrix)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [24]:
print(cm)

[[76  9]
 [ 8 41]]

In [25]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)

In [26]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.90      0.89      0.90        85
           1       0.82      0.84      0.83        49

    accuracy                           0.87       134
   macro avg       0.86      0.87      0.86       134
weighted avg       0.87      0.87      0.87       134

In [30]:
#f1 score prediction

from sklearn.metrics import f1_score
f1_weighted=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_weighted value for best parameter {}:".format(grid.best_params_),f1_weighted)

The f1_weighted value for best parameter {'criterion': 'entropy', 'max_features': None, 'random_state': None, 'splitter': 'best'}: 0.8733997218497793

In [31]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.8654261704681873