In [1]:
#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Loading Dataset
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
#checking counts-Rows&columns
dataset.shape

(399, 25)

In [5]:
#get dummies
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [7]:
#spliting Independent and Dependent
Independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv','wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes', 'pe_yes', 'ane_yes']]
Independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [8]:
Dependent=dataset[["classification_yes"]]
Dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Independent,Dependent, test_size = 1/3, random_state = 0)

In [10]:
#StandardScaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [11]:
#model creation
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy','log_loss'],'max_features': [None,'sqrt','log2'],'splitter':['best','random'],'random_state':[None]} 
grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'random_state': [None],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [12]:
grid_predictions = grid.predict(X_test)

In [13]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_random_state,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010015,0.002415,0.009635,0.001108,gini,None,None,best,"{'criterion': 'gini', 'max_features': None, 'r...",0.962963,0.981014,0.962573,0.943093,0.981031,0.966135,0.014121,4
1,0.007582,0.003197,0.008587,0.002883,gini,None,None,random,"{'criterion': 'gini', 'max_features': None, 'r...",0.926978,0.962264,0.944023,0.981217,1.000000,0.962896,0.025919,5
2,0.005821,0.002315,0.008671,0.001005,gini,sqrt,None,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.945100,0.942166,0.962573,0.962264,0.943651,0.951151,0.009247,11
3,0.007671,0.002293,0.009736,0.002557,gini,sqrt,None,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.963284,0.981233,0.888515,1.000000,0.981031,0.962813,0.038922,6
4,0.004761,0.000774,0.008803,0.002186,gini,log2,None,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.962963,0.942166,0.907035,0.962264,0.962264,0.947339,0.021637,13
5,0.004418,0.001940,0.008605,0.003029,gini,log2,None,random,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.943699,0.981217,1.000000,1.000000,0.984983,0.021886,1
6,0.005057,0.000695,0.007688,0.001375,entropy,None,None,best,"{'criterion': 'entropy', 'max_features': None,...",0.908501,0.903610,0.944023,0.903887,0.962264,0.924457,0.024185,17
7,0.005192,0.002081,0.006734,0.000855,entropy,None,None,random,"{'criterion': 'entropy', 'max_features': None,...",0.981569,0.962264,0.925524,0.962573,0.962573,0.958901,0.018254,9
8,0.003394,0.001311,0.010714,0.004015,entropy,sqrt,None,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.926978,0.922185,0.907035,0.981031,1.000000,0.947446,0.036277,12
9,0.002948,0.002908,0.009875,0.000638,entropy,sqrt,None,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.963284,0.961755,0.962264,0.981031,0.925524,0.958772,0.018124,10
10,0.003769,0.000443,0.006576,0.001532,entropy,log2,None,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.926567,0.942166,0.944023,0.943093,0.962264,0.943623,0.011322,14
11,0.002479,0.002178,0.009114,0.003621,entropy,log2,None,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.963284,0.962264,0.981217,0.944023,0.981217,0.966401,0.013904,3
12,0.006182,0.003425,0.007990,0.002003,log_loss,None,None,best,"{'criterion': 'log_loss', 'max_features': None...",0.890759,0.942166,0.888515,0.922492,0.962264,0.921239,0.028714,18
13,0.002790,0.000814,0.009584,0.001536,log_loss,None,None,random,"{'criterion': 'log_loss', 'max_features': None...",1.000000,0.962264,0.981217,0.962264,0.981217,0.977392,0.014129,2
14,0.005665,0.002556,0.007867,0.001251,log_loss,sqrt,None,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.944707,0.886792,0.943651,0.942332,0.905155,0.924528,0.024038,16
15,0.003435,0.001050,0.008094,0.002132,log_loss,sqrt,None,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.945100,0.943699,0.981217,0.962264,0.981217,0.962700,0.016473,7
16,0.005992,0.001523,0.009526,0.003227,log_loss,log2,None,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.945100,0.886792,0.944023,0.885478,0.961826,0.924644,0.032072,15
17,0.004305,0.000777,0.007305,0.001135,log_loss,log2,None,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.963284,0.962636,1.000000,0.925146,0.962264,0.962666,0.023673,8

In [14]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'log2', 'random_state': None, 'splitter': 'random'}

In [16]:
#evaluation metrics(confusion_matrix)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [17]:
print(cm)

[[49  2]
 [ 1 81]]

In [19]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [20]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      0.96      0.97        51
           1       0.98      0.99      0.98        82

    accuracy                           0.98       133
   macro avg       0.98      0.97      0.98       133
weighted avg       0.98      0.98      0.98       133

In [21]:
#f1 score prediction

from sklearn.metrics import f1_score
f1_weighted=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_weighted value for best parameter {}:".format(grid.best_params_),f1_weighted)

The f1_weighted value for best parameter {'criterion': 'gini', 'max_features': 'log2', 'random_state': None, 'splitter': 'random'}: 0.9774002964206194

In [22]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9742945958871354