In [1]:
#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Loading Dataset
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
#checking counts-Rows&columns
dataset.shape

(399, 25)

In [4]:
#get dummies
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
#How many classes we are going to classify
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [6]:
#spliting Independent and Dependent
Independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv','wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes', 'pe_yes', 'ane_yes']]
Independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [7]:
Dependent=dataset[["classification_yes"]]
Dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Independent,Dependent, test_size = 1/3, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [13]:
#model creation
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import GridSearchCV
param_grid ={'alpha': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],'force_alpha':[True,False], 'fit_prior' : [True, False]}
grid = GridSearchCV(CategoricalNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(Independent,Dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan]
  warnings.warn(
C:\Users\sswat\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=CategoricalNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,
                                   1.0],
                         'fit_prior': [True, False],
                         'force_alpha': [True, False]},
             scoring='f1', verbose=3)

In [14]:
grid_predictions = grid.predict(X_test)

In [15]:
#evaluation metrics(confusion_matrix)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [16]:
print(cm)

[[51  0]
 [ 1 81]]

In [17]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [18]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [19]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_fit_prior,param_force_alpha,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.034313,0.007102,0.010403,0.002936,0.1,True,True,"{'alpha': 0.1, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
1,0.017437,0.004042,0.012462,0.002549,0.1,True,False,"{'alpha': 0.1, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
2,0.026854,0.007825,0.013862,0.011583,0.1,False,True,"{'alpha': 0.1, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
3,0.025765,0.006584,0.010803,0.004639,0.1,False,False,"{'alpha': 0.1, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
4,0.023590,0.004492,0.012668,0.005206,0.2,True,True,"{'alpha': 0.2, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
5,0.020267,0.008181,0.007821,0.004000,0.2,True,False,"{'alpha': 0.2, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
6,0.026341,0.004509,0.013738,0.004905,0.2,False,True,"{'alpha': 0.2, 'fit_prior': False, 'force_alph...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
7,0.026210,0.006731,0.009338,0.004206,0.2,False,False,"{'alpha': 0.2, 'fit_prior': False, 'force_alph...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
8,0.019557,0.002075,0.009660,0.002187,0.3,True,True,"{'alpha': 0.3, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
9,0.021199,0.005396,0.009558,0.003125,0.3,True,False,"{'alpha': 0.3, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
10,0.016735,0.004897,0.012087,0.005488,0.3,False,True,"{'alpha': 0.3, 'fit_prior': False, 'force_alph...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
11,0.025612,0.003453,0.008878,0.003270,0.3,False,False,"{'alpha': 0.3, 'fit_prior': False, 'force_alph...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
12,0.023562,0.006360,0.006974,0.004096,0.4,True,True,"{'alpha': 0.4, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
13,0.020101,0.004629,0.019724,0.010077,0.4,True,False,"{'alpha': 0.4, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
14,0.022872,0.010266,0.009454,0.004356,0.4,False,True,"{'alpha': 0.4, 'fit_prior': False, 'force_alph...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
15,0.027007,0.010914,0.007341,0.008400,0.4,False,False,"{'alpha': 0.4, 'fit_prior': False, 'force_alph...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
16,0.027286,0.003447,0.008074,0.005442,0.5,True,True,"{'alpha': 0.5, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
17,0.019968,0.007697,0.014431,0.008145,0.5,True,False,"{'alpha': 0.5, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
18,0.021716,0.005803,0.011076,0.004935,0.5,False,True,"{'alpha': 0.5, 'fit_prior': False, 'force_alph...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
19,0.019590,0.006383,0.008281,0.001331,0.5,False,False,"{'alpha': 0.5, 'fit_prior': False, 'force_alph...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
20,0.020192,0.007939,0.011949,0.004582,0.6,True,True,"{'alpha': 0.6, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
21,0.025644,0.004368,0.010444,0.005064,0.6,True,False,"{'alpha': 0.6, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
22,0.025173,0.005311,0.009060,0.005463,0.6,False,True,"{'alpha': 0.6, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
23,0.019775,0.006548,0.009186,0.003666,0.6,False,False,"{'alpha': 0.6, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
24,0.019332,0.004900,0.010309,0.004150,0.7,True,True,"{'alpha': 0.7, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
25,0.018982,0.004194,0.008116,0.005797,0.7,True,False,"{'alpha': 0.7, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
26,0.019510,0.006491,0.011142,0.004589,0.7,False,True,"{'alpha': 0.7, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
27,0.020658,0.003366,0.008729,0.005308,0.7,False,False,"{'alpha': 0.7, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
28,0.022820,0.001996,0.009930,0.005233,0.8,True,True,"{'alpha': 0.8, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
29,0.026881,0.007835,0.002924,0.003523,0.8,True,False,"{'alpha': 0.8, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
30,0.017885,0.009550,0.014071,0.005968,0.8,False,True,"{'alpha': 0.8, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
31,0.026617,0.005582,0.007764,0.007618,0.8,False,False,"{'alpha': 0.8, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
32,0.027031,0.005488,0.006562,0.006280,0.9,True,True,"{'alpha': 0.9, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
33,0.022325,0.005543,0.012146,0.004778,0.9,True,False,"{'alpha': 0.9, 'fit_prior': True, 'force_alpha...",0.969697,NaN,NaN,NaN,NaN,NaN,NaN,1
34,0.025578,0.006641,0.007823,0.007106,0.9,False,True,"{'alpha': 0.9, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
35,0.028186,0.005363,0.005735,0.005335,0.9,False,False,"{'alpha': 0.9, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
36,0.020154,0.004478,0.014326,0.007411,1.0,True,True,"{'alpha': 1.0, 'fit_prior': True, 'force_alpha...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
37,0.021275,0.004954,0.006922,0.008470,1.0,True,False,"{'alpha': 1.0, 'fit_prior': True, 'force_alpha...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
38,0.025009,0.007112,0.009686,0.007911,1.0,False,True,"{'alpha': 1.0, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1
39,0.018215,0.003155,0.004899,0.006705,1.0,False,False,"{'alpha': 1.0, 'fit_prior': False, 'force_alph...",0.959184,NaN,NaN,NaN,NaN,NaN,NaN,1

In [22]:
print(grid.best_params_)

{'alpha': 0.1, 'fit_prior': True, 'force_alpha': True}

In [20]:
from sklearn.metrics import f1_score
f1_weighted=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_weighted value for best parameter {}:".format(grid.best_params_),f1_weighted)

The f1_weighted value for best parameter {'alpha': 0.1, 'fit_prior': True, 'force_alpha': True}: 0.9924946382275899

In [21]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0